In [1]:
import numpy as np

In [2]:
import axon.activation as activation

In [3]:
z = np.random.rand(5, 1)
z

array([[0.69851004],
       [0.46452282],
       [0.35992342],
       [0.8242941 ],
       [0.41296058]])

In [4]:
activation.Identity.sigma(z)

array([[0.69851004],
       [0.46452282],
       [0.35992342],
       [0.8242941 ],
       [0.41296058]])

In [5]:
activation.Identity.partial_sigma(z, z)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
activation.Relu.sigma(z)

array([[0.69851004],
       [0.46452282],
       [0.35992342],
       [0.8242941 ],
       [0.41296058]])

In [7]:
activation.Relu.partial_sigma(z, z)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [8]:
a = activation.Softmax.sigma(z)
a

array([[0.22780147],
       [0.18027569],
       [0.16237165],
       [0.25833535],
       [0.17121585]])

In [9]:
activation.Softmax.partial_sigma(z, a)

array([[ 0.17590796, -0.04106707, -0.0369885 , -0.05884917, -0.03900322],
       [-0.04106707,  0.14777636, -0.02927166, -0.04657158, -0.03086605],
       [-0.0369885 , -0.02927166,  0.1360071 , -0.04194634, -0.0278006 ],
       [-0.05884917, -0.04657158, -0.04194634,  0.1915982 , -0.04423111],
       [-0.03900322, -0.03086605, -0.0278006 , -0.04423111,  0.14190098]])

In [10]:
z

array([[0.69851004],
       [0.46452282],
       [0.35992342],
       [0.8242941 ],
       [0.41296058]])

In [11]:
a = activation.Sigmoid.sigma(z)
a

array([[0.66785735],
       [0.61408656],
       [0.5890219 ],
       [0.6951471 ],
       [0.60179756]])

In [12]:
activation.Sigmoid.partial_sigma(z, a)

array([[0.22182391, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.23698426, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.2420751 , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.21191761, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.23963726]])