In [1]:
import numpy as np

In [2]:
import activation

In [5]:
z = np.random.rand(5, 1)
z

array([[0.74390156],
       [0.8764809 ],
       [0.47600885],
       [0.00121147],
       [0.37518496]])

In [6]:
activation.Identity.sigma(z)

array([[0.74390156],
       [0.8764809 ],
       [0.47600885],
       [0.00121147],
       [0.37518496]])

In [8]:
activation.Identity.partial_sigma(z, z)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
activation.Relu.sigma(z)

array([[0.74390156],
       [0.8764809 ],
       [0.47600885],
       [0.00121147],
       [0.37518496]])

In [11]:
activation.Relu.partial_sigma(z, z)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [13]:
a = activation.Softmax.sigma(z)
a

array([[0.24544618],
       [0.28024298],
       [0.18776383],
       [0.11679118],
       [0.16975582]])

In [14]:
activation.Softmax.partial_sigma(z, a)

array([[ 0.18520235, -0.06878457, -0.04608591, -0.02866595, -0.04166592],
       [-0.06878457,  0.20170685, -0.0526195 , -0.03272991, -0.04757288],
       [-0.04608591, -0.0526195 ,  0.15250858, -0.02192916, -0.031874  ],
       [-0.02866595, -0.03272991, -0.02192916,  0.103151  , -0.01982598],
       [-0.04166592, -0.04757288, -0.031874  , -0.01982598,  0.14093878]])