In [23]:
import numpy as np

In [24]:
import activation

In [25]:
z = np.random.rand(5, 1)
z

array([[0.93208915],
       [0.3137137 ],
       [0.95548098],
       [0.19615826],
       [0.04507771]])

In [26]:
activation.Identity.sigma(z)

array([[0.93208915],
       [0.3137137 ],
       [0.95548098],
       [0.19615826],
       [0.04507771]])

In [27]:
activation.Identity.partial_sigma(z, z)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
activation.Relu.sigma(z)

array([[0.93208915],
       [0.3137137 ],
       [0.95548098],
       [0.19615826],
       [0.04507771]])

In [29]:
activation.Relu.partial_sigma(z, z)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [30]:
a = activation.Softmax.sigma(z)
a

array([[0.28956712],
       [0.15602428],
       [0.29642047],
       [0.13871982],
       [0.11926831]])

In [31]:
activation.Softmax.partial_sigma(z, a)

array([[ 0.205718  , -0.0451795 , -0.08583362, -0.0401687 , -0.03453618],
       [-0.0451795 ,  0.13168071, -0.04624879, -0.02164366, -0.01860875],
       [-0.08583362, -0.04624879,  0.20855537, -0.04111939, -0.03535357],
       [-0.0401687 , -0.02164366, -0.04111939,  0.11947663, -0.01654488],
       [-0.03453618, -0.01860875, -0.03535357, -0.01654488,  0.10504338]])

In [32]:
z

array([[0.93208915],
       [0.3137137 ],
       [0.95548098],
       [0.19615826],
       [0.04507771]])

In [34]:
a = activation.Sigmoid.sigma(z)
a

array([[0.71749894],
       [0.57779147],
       [0.72221611],
       [0.54888292],
       [0.51126752]])

In [35]:
activation.Sigmoid.partial_sigma(z, a)

array([[0.20269421, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.24394849, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.20062   , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.24761046, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.24987304]])