In [18]:
import numpy as np

In [19]:
from axon import layer
from axon.optimizer import Optimizer

In [20]:
l = layer.Layer(5, 4)

In [21]:
l.weights

array([[0.24787226, 0.1012496 , 0.2353784 , 0.14740689, 0.26809284],
       [0.37219947, 0.10693799, 0.16165955, 0.32967753, 0.02952546],
       [0.34410322, 0.29951269, 0.06210027, 0.04787211, 0.24641171],
       [0.0754713 , 0.26222132, 0.18979226, 0.32572954, 0.14678558]])

In [22]:
i = np.random.rand(5, 1)
i

array([[0.84552626],
       [0.44186747],
       [0.34471494],
       [0.14171696],
       [0.97548493]])

In [23]:
output = l.forward(Optimizer.SGD, i, None)
output

array([[0.89431985],
       [0.55920332],
       [0.71983801],
       [0.48186571]])

In [24]:
target = np.random.rand(4, 1)
target

array([[0.15857   ],
       [0.47190107],
       [0.77467007],
       [0.93206715]])

In [25]:
from axon import loss

In [26]:
partials = loss.MSE.partial_loss(output, target)
partials

array([[ 1.47149969],
       [ 0.17460451],
       [-0.10966413],
       [-0.90040287]])

In [27]:
l.weights

array([[0.24787226, 0.1012496 , 0.2353784 , 0.14740689, 0.26809284],
       [0.37219947, 0.10693799, 0.16165955, 0.32967753, 0.02952546],
       [0.34410322, 0.29951269, 0.06210027, 0.04787211, 0.24641171],
       [0.0754713 , 0.26222132, 0.18979226, 0.32572954, 0.14678558]])

In [28]:
l.backward(Optimizer.SGD, partials, 0.05, None, None, None)

array([[ 0.32404131],
       [-0.10129001],
       [ 0.19688607],
       [-0.02406529],
       [ 0.24046513]])

In [29]:
l.weights

array([[0.18566268, 0.06873921, 0.21001601, 0.13698007, 0.19632155],
       [0.36481783, 0.10308039, 0.15865012, 0.32844031, 0.02100926],
       [0.34873941, 0.30193554, 0.06399041, 0.04864917, 0.2517605 ],
       [0.11353701, 0.28211425, 0.20531137, 0.33210966, 0.19070205]])