In [17]:
import numpy as np

In [18]:
import layer

In [19]:
l = layer.Layer(5, 4)

In [20]:
l.weights

array([[0.78923625, 0.94315359, 0.34432494, 0.90264165, 0.44385305],
       [0.80469089, 0.39102893, 0.99909259, 0.39706384, 0.88279725],
       [0.37809953, 0.70878172, 0.55352421, 0.94667081, 0.24797929],
       [0.80491856, 0.09290484, 0.2722178 , 0.22030843, 0.87840769]])

In [21]:
i = np.random.rand(5, 1)
i

array([[0.31854312],
       [0.27531755],
       [0.99034287],
       [0.9856298 ],
       [0.20655805]])

In [22]:
output = l.forward(i)
output

array([[2.20624167],
       [2.67325049],
       [2.59940465],
       [1.39256186]])

In [23]:
target = np.random.rand(4, 1)
target

array([[0.97264693],
       [0.94306628],
       [0.20255989],
       [0.43274681]])

In [24]:
import loss

In [25]:
partials = loss.MSE.partial_loss(output, target)
partials

array([[2.46718948],
       [3.46036843],
       [4.79368952],
       [1.91963009]])

In [26]:
l.weights

array([[0.78923625, 0.94315359, 0.34432494, 0.90264165, 0.44385305],
       [0.80469089, 0.39102893, 0.99909259, 0.39706384, 0.88279725],
       [0.37809953, 0.70878172, 0.55352421, 0.94667081, 0.24797929],
       [0.80491856, 0.09290484, 0.2722178 , 0.22030843, 0.87840769]])

In [27]:
l.backward(partials, 0.05)

array([[8.08935993],
       [7.25606523],
       [7.48272402],
       [8.56193178],
       [7.02482685]])

In [28]:
l.weights

array([[0.74994094, 0.90919056, 0.22215676, 0.78105488, 0.41837216],
       [0.74957706, 0.34339393, 0.82774503, 0.22653173, 0.8470589 ],
       [0.30174969, 0.64279238, 0.3161544 , 0.71043064, 0.19847053],
       [0.77434431, 0.06647945, 0.1771632 , 0.1257062 , 0.85858194]])