In [20]:
import numpy as np

In [21]:
import axon.loss as loss

In [22]:
output = np.random.rand(4, 1)
output

array([[0.32780393],
       [0.55999308],
       [0.05360703],
       [0.47403565]])

In [23]:
target = np.random.rand(4, 1)
target

array([[0.23085897],
       [0.36919241],
       [0.30202032],
       [0.62865935]])

In [24]:
axon.loss.MSE.loss(output, target)

0.13142087017220666

In [25]:
incorrect_label = np.random.rand(1, 1)
incorrect_label

array([[0.41375521]])

In [26]:
loss.MSE.loss(output, incorrect_label)

AssertionError: 

In [27]:
loss.Logistic.loss(output, target)

1.8245665132868893

In [28]:
loss.MSE.partial_loss(output, target)

array([[ 0.19388991],
       [ 0.38160133],
       [-0.49682658],
       [-0.3092474 ]])

In [29]:
loss.Logistic.partial_loss(output, target)

array([[-0.70425932],
       [-0.65928032],
       [-5.63396837],
       [-1.32618581]])