In [1]:
import numpy as np

In [2]:
import loss

In [3]:
output = np.random.rand(4, 1)
output

array([[0.53781344],
       [0.41453197],
       [0.27817388],
       [0.08542682]])

In [5]:
target = np.random.rand(4, 1)
target

array([[0.20425376],
       [0.95370953],
       [0.68727585],
       [0.08654037]])

In [6]:
loss.MSE.loss(output, target)

0.5693401659931289

In [7]:
incorrect_label = np.random.rand(1, 1)
incorrect_label

array([[0.43591426]])

In [8]:
loss.MSE.loss(output, incorrect_label)

AssertionError: 

In [9]:
loss.Logistic.loss(output, target)

2.058801718013849

In [10]:
loss.MSE.partial_loss(output, target)

array([[ 0.66711937],
       [-1.07835512],
       [-0.81820394],
       [-0.00222709]])

In [11]:
loss.Logistic.partial_loss(output, target)

array([[-0.37978552],
       [-2.30068992],
       [-2.47066996],
       [-1.01303509]])