In [1]:
import numpy as np

In [2]:
inputs = 4
outputs = 3
weights = np.random.rand(2, 3)
weights

array([[0.76431957, 0.94651489, 0.73744036],
       [0.29893787, 0.07544223, 0.71504593]])

In [3]:
biases = np.random.rand(2, 1)
biases

array([[0.16720052],
       [0.29454379]])

In [4]:
input = np.random.rand(3, 3)
input

array([[0.09249898, 0.34585562, 0.27546927],
       [0.19999078, 0.08684445, 0.94278697],
       [0.82458268, 0.38423681, 0.78870838]])

In [5]:
output = np.add(np.matmul(weights, input), biases)
output

array([[1.03527409, 0.79709604, 1.85173437],
       [0.92689748, 0.67923184, 1.01198065]])

In [6]:
output = np.matmul(weights, input) + biases
output

array([[1.03527409, 0.79709604, 1.85173437],
       [0.92689748, 0.67923184, 1.01198065]])

In [7]:
np.matmul(weights, input) + biases

array([[1.03527409, 0.79709604, 1.85173437],
       [0.92689748, 0.67923184, 1.01198065]])

In [8]:
r = lambda x: 0 if x < 0 else x


In [9]:
pre_hessian = np.matmul(output, output.T)
display(pre_hessian)

array([[5.13607471, 3.37492531],
       [3.37492531, 2.34459968]])

In [10]:
dz_dw = np.tile(input.T, (2, 1))
dz_dw

array([[0.09249898, 0.19999078, 0.82458268],
       [0.34585562, 0.08684445, 0.38423681],
       [0.27546927, 0.94278697, 0.78870838],
       [0.09249898, 0.19999078, 0.82458268],
       [0.34585562, 0.08684445, 0.38423681],
       [0.27546927, 0.94278697, 0.78870838]])

In [11]:
de_da = np.array([[2], [1]])
de_da

array([[2],
       [1]])

In [12]:
from axon import activation

In [13]:
act = activation.Relu
a = act.sigma(output)
a

array([[1.03527409, 0.79709604, 1.85173437],
       [0.92689748, 0.67923184, 1.01198065]])

In [14]:
da_dz = act.partial_sigma(output, a)
da_dz

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [15]:
act = activation.Softmax
a = act.sigma(output)
a

array([[0.52706766, 0.52943198, 0.69841334],
       [0.47293234, 0.47056802, 0.30158666]])

In [16]:
target = np.array([[1], [0]])
loss_ = np.square(target - a)
loss_

array([[0.22366499, 0.22143426, 0.09095451],
       [0.22366499, 0.22143426, 0.09095451]])

In [17]:
loss = np.sum(loss_)
loss

1.0721075257173762

In [18]:
-2 * (target - a)

array([[-0.94586467, -0.94113603, -0.60317331],
       [ 0.94586467,  0.94113603,  0.60317331]])

In [19]:
-(target/a)

array([[-1.8972896 , -1.88881675, -1.43181686],
       [-0.        , -0.        , -0.        ]])

In [20]:
i = np.random.rand(1, 3)
i

array([[0.15208798, 0.55186479, 0.80091234]])

In [21]:
np.tile(i, (3, 1))

array([[0.15208798, 0.55186479, 0.80091234],
       [0.15208798, 0.55186479, 0.80091234],
       [0.15208798, 0.55186479, 0.80091234]])

In [22]:
-2 * (i - i)

array([[-0., -0., -0.]])

In [23]:
np.sum(a, axis=1)[np.newaxis].T

array([[1.75491299],
       [1.24508701]])