In [1]:
import numpy as np

In [2]:
inputs = 4
outputs = 3
weights = np.random.rand(2, 3)
weights

array([[0.05431754, 0.45389262, 0.55894895],
       [0.02587451, 0.91887833, 0.03197778]])

In [3]:
biases = np.random.rand(2, 1)
biases

array([[0.57257984],
       [0.04441822]])

In [4]:
input = np.random.rand(3, 1)
input

array([[0.57229718],
       [0.6942631 ],
       [0.66311116]])

In [5]:
output = np.add(np.matmul(weights, input), biases)
output

array([[1.2894318 ],
       [0.71837427]])

In [6]:
np.matmul(weights, input) + biases

array([[1.2894318 ],
       [0.71837427]])

In [7]:
r = lambda x: 0 if x < 0 else x


In [8]:
pre_hessian = np.matmul(output, output.T)
display(pre_hessian)

array([[1.66263436, 0.92629463],
       [0.92629463, 0.5160616 ]])

In [9]:
diagonal = np.diagflat(output)
display(diagonal)

array([[1.2894318 , 0.        ],
       [0.        , 0.71837427]])

In [10]:
da_dz = pre_hessian + diagonal
da_dz

array([[2.95206616, 0.92629463],
       [0.92629463, 1.23443587]])

In [11]:
dz_dw = np.tile(input.T, (2, 1))
dz_dw

array([[0.57229718, 0.6942631 , 0.66311116],
       [0.57229718, 0.6942631 , 0.66311116]])

In [12]:
de_da = np.array([[2], [1]])
de_da

array([[2],
       [1]])

In [13]:
de_dz = np.matmul(da_dz, de_da)
de_dz

array([[6.83042694],
       [3.08702514]])

In [14]:
de_dw = de_dz * dz_dw
de_dw

array([[3.90903409, 4.74211341, 4.52933233],
       [1.76669579, 2.14320766, 2.04704082]])

In [15]:
de_dx = np.matmul(weights.T, de_dz)
de_dx

array([[0.45088723],
       [5.93688089],
       [3.91657618]])

In [16]:
weights = weights - (0.05 * de_dw)
weights

array([[-0.14113417,  0.21678695,  0.33248234],
       [-0.06246028,  0.81171795, -0.07037426]])

In [17]:
import activation

In [20]:
act = activation.Relu
a = act.sigma(output)
a

array([[1.2894318 ],
       [0.71837427]])

In [21]:
da_dz = act.partial_sigma(output, a)
da_dz

array([[1., 0.],
       [0., 1.]])

In [22]:
act = activation.Softmax
a = act.sigma(output)
a

array([[0.63900716],
       [0.36099284]])

In [23]:
da_dz = act.partial_sigma(output, a)
da_dz

array([[ 0.23067701, -0.23067701],
       [-0.23067701,  0.23067701]])