In [ ]:
import numpy as np

In [5]:
inputs = 4
outputs = 3
weights = np.random.rand(2, 3)
weights

array([[0.34026941, 0.36039005, 0.61900299],
       [0.06559809, 0.04933461, 0.34848933]])

In [6]:
biases = np.random.rand(2, 1)
biases

array([[0.6255238 ],
       [0.42581633]])

In [7]:
input = np.random.rand(3, 1)
input

array([[0.51970884],
       [0.60721416],
       [0.63800517]])

In [13]:
output = np.add(np.matmul(weights, input), biases)
output

array([[1.41612587],
       [0.7122029 ]])

In [15]:
r = lambda x: 0 if x < 0 else x


array([1.41612587])

In [ ]:
np.matmul(output, output.T)