In [67]:
import numpy as np

In [68]:
inputs = 4
outputs = 3
weights = np.random.rand(2, 3)
weights

array([[0.76201386, 0.40645166, 0.37265552],
       [0.84542772, 0.36255057, 0.57989016]])

In [69]:
biases = np.random.rand(2, 1)
biases

array([[0.24248414],
       [0.66814972]])

In [70]:
input = np.random.rand(3, 3)
input

array([[0.52211698, 0.86661387, 0.52582117],
       [0.98436268, 0.13793539, 0.78786952],
       [0.40709734, 0.96364339, 0.42279671]])

In [71]:
output = np.add(np.matmul(weights, input), biases)
output

array([[1.19214743, 1.31802702, 1.12095556],
       [1.70251487, 2.00962498, 1.6435117 ]])

In [72]:
output = np.matmul(weights, input) + biases
output

array([[1.19214743, 1.31802702, 1.12095556],
       [1.70251487, 2.00962498, 1.6435117 ]])

In [73]:
np.matmul(weights, input) + biases

array([[1.19214743, 1.31802702, 1.12095556],
       [1.70251487, 2.00962498, 1.6435117 ]])

In [74]:
r = lambda x: 0 if x < 0 else x


In [75]:
pre_hessian = np.matmul(output, output.T)
display(pre_hessian)

array([[4.41495207, 6.52069231],
       [6.52069231, 9.63828014]])

In [76]:
dz_dw = np.tile(input.T, (2, 1))
dz_dw

array([[0.52211698, 0.98436268, 0.40709734],
       [0.86661387, 0.13793539, 0.96364339],
       [0.52582117, 0.78786952, 0.42279671],
       [0.52211698, 0.98436268, 0.40709734],
       [0.86661387, 0.13793539, 0.96364339],
       [0.52582117, 0.78786952, 0.42279671]])

In [77]:
de_da = np.array([[2], [1]])
de_da

array([[2],
       [1]])

In [78]:
import activation

In [79]:
act = activation.Relu
a = act.sigma(output)
a

array([[1.19214743, 1.31802702, 1.12095556],
       [1.70251487, 2.00962498, 1.6435117 ]])

In [80]:
da_dz = act.partial_sigma(output, a)
da_dz

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [81]:
act = activation.Softmax
a = act.sigma(output)
a

array([[0.37510739, 0.33367769, 0.37225472],
       [0.62489261, 0.66632231, 0.62774528]])

In [82]:
target = np.array([[1], [0]])
loss_ = np.square(target - a)
loss_

array([[0.39049077, 0.44398541, 0.39406414],
       [0.39049077, 0.44398541, 0.39406414]])

In [83]:
loss = np.sum(loss_)
loss

2.457080654786957

In [84]:
-2 * (target - a)

array([[-1.24978522, -1.33264461, -1.25549057],
       [ 1.24978522,  1.33264461,  1.25549057]])

In [85]:
-(target/a)

array([[-2.66590321, -2.99690395, -2.68633265],
       [-0.        , -0.        , -0.        ]])

In [86]:
i = np.random.rand(1, 3)
i

array([[0.95659994, 0.34929142, 0.63868779]])

In [87]:
np.tile(i, (3, 1))

array([[0.95659994, 0.34929142, 0.63868779],
       [0.95659994, 0.34929142, 0.63868779],
       [0.95659994, 0.34929142, 0.63868779]])

In [88]:
-2 * (i - i)

array([[-0., -0., -0.]])

In [91]:
np.sum(a, axis=1)[np.newaxis].T

array([[1.0810398],
       [1.9189602]])